### ISSUE TITLE
Composition API?

### ISSUE THREAD

**Issue by NikitaKA** [ktsn/vuex-smart-module#106]
Is that possible (or how to do that in proper way?) to use `vuex-smart-module` with new `Composition API` (as `Vue 2` plugin)?

**Comment by ktsn** [comment]
Yes, I'm going to support it!

**Comment by nicolidin** [comment]
Is there a version to already test it with vue3 ?

**Comment by CoskunSunali** [comment]
> Is there a version to already test it with vue3 ?

I am also pretty curious of the same thing. Planning to migrate some projects from Vue 2 to 3 and vuex-smart-module is the only remaining uncertainty for me.

**Comment by laurisstepanovs** [comment]
@ktsn Can you please estimate when it will be done?

**Comment by nicolidin** [comment]
@ktsn this library is really important for a lot of vue typescript class users.  And as vue-class-component and vue-property-decorator is now working really great with vue3, **Vuex-Smart-Module** is the only staying library that needs to support Vue3!
We need you more than ever @ktsn!

**Comment by LifeIsStrange** [comment]
Hi @kaorun343 given that you recently made vue-property-decorator compliant with Vue 3, I wonder if you might help @ktsn with making vuex-smart-module compliant with Vuex4 given that those libraries are relatively similar in the Vue Class ideology, that would be wonderful.
Few people have the required expertise to make such a contribution and I believe that you have such expertise related to typescript meta-programming/reflection/vue APIs.

**Comment by nicolidin** [comment]
@yyx990803 I affoard to tag you in this issue because this library is the last wall that prevent a lot of vuejs typescript user to go on Vue3. Indeed this library is the only one that allow to do abstraction based

**Comment by nicolidin** [comment]
Hi @yyx990803, I afford to tag you on this issue because it is the only one that still prevents a lot of vue typescript developers to be able to move on vue3.
I, my team, and a lot of other vue-typescript developers need this library mainly because it allows doing abstraction on vuex stores by creating class, abstract class, and interfaces for each _Action_, _Mutation_, _Getter_ and _State_.
Sadly, @ktsn does not contribute anymore to vuejs projects for a long time and not a lot of developers can contribute to vuex-smart-modules because it requires a lot of knowledge about javascript reflections and especially cause this library needs to be totally **compliant** with the **vuex API**.

We really hope, @yyx990803, you can do something to help the community (or other vue developers as @posva?) because it's been a lot of months we are waiting for this specific library to be compliant with vue3 and thus to allow us to move on vue3.
Thanks a lot,

BTW: this library is definitely not enough famous and I think it could be interesting to move it to the Vuejs organization (it could be in synergy with vue-class-component).

**Comment by posva** [comment]
Hi @nicolidin 

I don't have the bandwidth to take the time to do a PR on this project and I don't use it personally. I think it would make sense for people using this project to do a PR. When it comes to TS, Stores, and Vue 3, I'm focused on https://github.com/posva/pinia, helping out with Vuex 5 (https://github.com/vuejs/rfcs/discussions/270) and making pinia' API as close as Vuex 5 to ease migration in the future.

**Comment by nicolidin** [comment]
Actually, we were wrong (@NikitaKA, @CoskunSunali, @laurisstepanovs), _vuex-smart-module_ works with vue3, I think this issue can be close @ktsn.
Sorry for all those previous requests yyx990803, posva, kiaking and ktsn.
Thanks!
(I still think it could be a great idea to move this repo into the Vue organization!)
