### ISSUE TITLE
Add support Global Action in Namespaced Modules

### ISSUE THREAD

**Issue by tyllo** [ktsn/vuex-smart-module#271]
I needs this feature of vuex modules [Register Global Action in Namespaced Modules](https://vuex.vuejs.org/guide/modules.html#register-global-action-in-namespaced-modules)

**Comment by ktsn** [comment]
Thanks for filing the issue. But this is out of the scope of this project because one of the goals is type-safe usage of Vuex store which cannot be achieved with global action usage.

You can still use root-level/other namespace actions by using the context feature.

https://github.com/ktsn/vuex-smart-module#module-lifecycle-and-dependencies

**Comment by tyllo** [comment]
Щr you can just leave all the root actions in Action, or they'll disappear.

**Comment by tyllo** [comment]
I needs root action `logout` for clear all subordinate stores
