### ISSUE TITLE
"Module" is referenced directly or indirectly in its own type annotation

### ISSUE THREAD

**Issue by MateiNenciu** [ktsn/vuex-smart-module#30]
I created an test repo for exposing this issue, you can find it here: https://github.com/MateiNenciu/nuxt-vuex-smart-module-test

  Problem is highlighted here: https://github.com/MateiNenciu/nuxt-vuex-smart-module-test/blob/master/store/modules/Login/actions.ts#L20 . I believe this issue appear because Login is listed as a nested module in Root. We import RootModule inside LoginModule because in root we have several mutations that might get called depending of the situation ( an error log for example, look in LoginModule actions at that addError call example). 
  This issue only appears in version 0.3.0, if you downgrade the package to 0.2.7 version it shows no error.

  Is this a bug or we should move the logic from RootModule to another nested module ?

**Comment by ktsn** [comment]
I just figured out the cause. This error is caused by this type. https://github.com/ktsn/vuex-smart-module/blob/master/src/assets.ts#L91

The `Actions` class is recursive type by its own type `A`. Somehow the recursion with `Dispatch<A>` is not a problem but we cannot use `A` with mapped types which is used in `Dispatcher<A>`.

Possible solution is replacing `Dispatcher<A>` with just `A` but it does not describe `actions` type correctly.

**Comment by ktsn** [comment]
Work around would be:

- Avoid circular reference of modules as OP said.
- Do not specify the 4th type parameter when you do not use `dispatch` or `actions` in any actions in the same module.

**Comment by ktsn** [comment]
Fixed it on v0.3.1 by the approach what I said earlier.
