### ISSUE TITLE
comparison of vuex-smart-module with vuex-module-decorators

### ISSUE THREAD

**Issue by cainrus** [ktsn/vuex-smart-module#31]
Hello, Ktsn. It's great repo.
I just wanted to know about benefits of vuex-smart-module over vuex-module-decorators.
So many technologies, libs and approaches. So I just do not sure if I need to try to use vuex-smart-module in my next projects? Is it more comfortable API?  better TS support? Or something else?

**Comment by ilajosmanov** [comment]
Sure! This package much better. I know about types in all application. Auto suggesting actions/getters/mutations/state in `.vue` files.

**Comment by ktsn** [comment]
Thank you for being interested in this lib!
Here are pros and cons of vuex-smart-module compared with vuex-module-decorators (in my perspective). Note that this list is probably biased as I haven't used vuex-module-decorators in actual project.

## Pros

- Not relying on experimental decorator which means less risk of breakage due to in progress standard.
- Better control accessible resources (e.g. you shouldn't access state/getters/actions in a mutation and vuex-smart-module prohibits it on type-level by API design)
- Testing support (https://github.com/ktsn/vuex-smart-module#testing)
- Module lifecycle support (https://github.com/ktsn/vuex-smart-module#module-lifecycle-and-dependencies)
- Do not need to consider matching namespace string as it will be automatically resolved.

## Cons

- Need to write more code as state/getters/mutations/actions are separated.
- It maybe hard to partially apply it to existing code base as you need to use `createStore` function from vuex-smart-module to create Vuex store.
