### ISSUE TITLE
hwo to use vuex-smart-module with router?

### ISSUE THREAD

**Issue by wizardnet972** [ktsn/vuex-smart-module#54]
How to use `vuex-smart-module` with router? 

for example I want in logout action to redirect to homepage.

**Comment by ktsn** [comment]
You can import your router instance and call redirect in your logout action.

**Comment by wizardnet972** [comment]
@ktsn But what if I use ssr? I have function create Router. Or I loading the store by code splitting?

**Comment by ktsn** [comment]
Please provide enough info in the next time. It is so difficult to guess your background from the original post because I'm not psychic.

I assume you are using Nuxt, in that case the standard way would be to inject router instance to store instance like [axios-module](https://axios.nuxtjs.org/) does. You can inject it via [plugin](https://nuxtjs.org/guide/plugins).
And you can use this technique to access store instance in vuex-smart-module: https://github.com/ktsn/vuex-smart-module#module-lifecycle-and-dependencies

In any cases this is common Vuex/SSR question rather than vuex-smart-module so you may want to ask it and gather some ideas from Vuex/Nuxt community.
